jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout the code
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Run Unit test
      uses: reactivecircus/android-emulator-runner@v2.20.0
      with:
        api-level: 30
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew createDebugCoverageReport
    - continue-on-error: true
      name: Lint
      run: ./gradlew lint
    - continue-on-error: true
      if: always()
      name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Report
        path: /Users/runner/work/mixpanel-android/mixpanel-android/build/reports/androidTests/connected
    - continue-on-error: true
      name: Upload test coverage report
      uses: actions/upload-artifact@v2
      with:
        name: Test Coverage Report
        path: /Users/runner/work/mixpanel-android/mixpanel-android/build/reports/coverage/debug/
    - continue-on-error: true
      name: Upload lint report
      uses: actions/upload-artifact@v2
      with:
        name: Lint Report
        path: /Users/runner/work/mixpanel-android/mixpanel-android/build/reports/lint-results.html
    - continue-on-error: true
      name: Android docs
      run: ./gradlew --info androidJavadocs
name: Mixpanel Android Pull Request and master branch CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
